name: Workflow de evente con github actions

on:
  push:
    branch:
      - 'feature/**'

jobs:
  checkout-branch:
    runs-on: ubuntu-latest

    steps: 
    - name: Mostrar informacion del evento
      run: |
        echo "Repositorio: $GITHUB_REPOSITORY"
        echo "Rama: $GITHUB_REF"
        echo "Actor: $GITHUB_ACTOR"

